---
extends: default
rules:
  line-length:
    max: 120
    level: warning
  document-start: enable
  trailing-spaces: enable
  new-line-at-end-of-file: enable
  indentation:
    spaces: 2
    indent-sequences: true
  truthy: disable
