services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alembic_app
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://myuser:mypassword@db:5432/mydb
    command: ["bash", "/app/start.sh"] # keeping the app container alive


volumes:
  db_data:
