app:
  name: db-app
  image:
    repository: haleema22/dockes_files01-app
    tag: latest
    pullPolicy: IfNotPresent
  port: 8000
  env:
    DATABASE_URL: postgresql+psycopg2://myuser:mypassword@postgres:5432/mydb
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15"
  database:
    name: mydb
    user: myuser
    password: mypassword
  port: 5432
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false