global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['web:8000']

  - job_name: redis-exporter
    static_configs:
      - targets: ['redis_exporter:9121']

rule_files:
  - "/etc/prometheus/alert_rules.yml"