apiVersion: v1
kind: Service
metadata:
  name: myesi-api-gateway
  namespace: myesi
spec:
  selector:
    app: myesi-api-gateway
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080