gateway:
  image: dquang0504/myesi-api-gateway:latest
  port: 8000
  pullPolicy: Always
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "100m"
  env:
    DATABASE_URL: postgresql+psycopg2://myesi:123456789@postgres:5432/myesi_db
    REDIS_URL: redis://redis:6379/0
    USER_SERVICE_URL: http://myesi-user-service:8001
    SBOM_SERVICE_URL: http://myesi-sbom-service:8002
    SECRET_KEY: replace-with-secure-key
  tlsSecretName: myesi-gateway-tls
  tlsCertPath: /app/certs/tls.crt
  tlsKeyPath: /app/certs/tls.key