postgres:
  enabled: true
  image:
    repository: postgres
    tag: "15"
  port: 5432
  database: 
    name: "myesi_db"
    user: "myesi"
    password: "123456789"
  storage:
    size: 1Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 250m